# Generated by Django 5.2.1 on 2025-05-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextToSpeechAdminLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Text-to-Speech',
                'verbose_name_plural': 'Text-to-Speech',
            },
        ),
    ]
