# Generated by Django 5.2.1 on 2025-05-22 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_texttospeech_delete_texttospeechadminlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='articles/videos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='news.article')),
            ],
        ),
    ]
